variables:
  GIT_SUBMODULE_STRATEGY: recursive
  ARTIFACT_STORAGE_DIR: "/srv/builds/artifacts"
  REGISTRY_PREFIX: "registry.gitlab.com/chriz2600"
  FW_UTILS_VERSION: "1.1.1_quartus-19.1.0"
  PIO_VERSION: "4.3.4"

stages:
  - build-fpga
  - build-esp
  - prepare-folders
  - publish

fpga-firmware:
  image:
    name: "${REGISTRY_PREFIX}/firmware-utils/firmware-utils:${FW_UTILS_VERSION}"
  stage: build-fpga
  script: 
    - ./Core/source/ram/create_text_ram.pl
    - script -qfc "$(printf "%q " "./Core/build-all")" /dev/null
  artifacts:
    name: "fpga-firmware-${CI_COMMIT_REF_NAME}"
    paths:
      - Core/output_files/std/*.jic
      - Core/output_files/std/*.rbf
      - Core/output_files/std/*.dc
      - Core/output_files/hq2x/*.jic
      - Core/output_files/hq2x/*.rbf
      - Core/output_files/hq2x/*.dc
      - Core/output_files/*.dc
      - Core/output_files/*.jic
      - Core/output_files/*.rbf
      - Core/output_files/DCxPlus-diag.bin
  tags:
    - docker
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

esp-firmware:
  image:
    name: "${REGISTRY_PREFIX}/platformio:${PIO_VERSION}"
  stage: build-esp
  script:
    - "./ESP/build-all"
  artifacts:
    name: "esp-firmware-${CI_COMMIT_REF_NAME}"
    paths:
      - ESP/.pio/build/std/firmware.bin
      - ESP/.pio/build/std/spiffs.bin
      - ESP/.pio/build/hq2x/firmware.bin
      - ESP/.pio/build/hq2x/spiffs.bin
      - ESP/.pio/build/firmware.bin
      - ESP/.pio/build/spiffs.bin
      - ESP/data/index.html.gz
      - ESP/data/changelog
  dependencies:
    - fpga-firmware
  tags:
    - docker
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

prepare-folders:
  image:
    name: "${REGISTRY_PREFIX}/firmware-utils/dc-publish-utils:${FW_UTILS_VERSION}"
  stage: prepare-folders
  script:
    - "mkdir -p docroot/fw/${CI_COMMIT_REF_NAME}"
    - "cp Core/output_files/DCxPlus-diag.bin docroot/fw/${CI_COMMIT_REF_NAME}/"
    - "prepare-fpga-branch-folder std"
    - "prepare-fpga-branch-folder hq2x"
    - "prepare-fpga-branch-folder"
    - "prepare-esp-branch-folder std ESP"
    - "prepare-esp-branch-folder hq2x ESP"
    - "prepare-esp-branch-folder '' ESP"
  artifacts:
    name: "docroot-${CI_COMMIT_REF_NAME}"
    paths:
      - "docroot"
  dependencies:
    - fpga-firmware
    - esp-firmware
  tags:
    - docker
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags

finish-publish:
  image:
    name: "${REGISTRY_PREFIX}/firmware-utils/dc-publish-utils:${FW_UTILS_VERSION}"
  stage: publish
  script:
    - "atomic-move /srv/incoming std"
    - "atomic-move /srv/incoming hq2x"
    - "atomic-move /srv/incoming"
    - "create-index-html /srv/incoming/fw root-index.html.fpga.j2"
    - "create-index-html /srv/incoming/esp root-index.html.esp.j2"
  artifacts:
    expire_in: 1 sec
  dependencies:
    - prepare-folders
  tags:
    - docker
  only:
    - develop
    - master
    - experimental
    - bleeding
    - tags
